development:
  executor:
    class: ExecutorJob
    schedule: "every <%= Rails.application.config.executor_seconds %> seconds"
  cleanup:
    class: CleanupJob
    schedule: "every day at 1am"

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  executor:
    class: ExecutorJob
    schedule: "every <%= Rails.application.config.executor_seconds %> seconds"
  cleanup:
    class: CleanupJob
    schedule: "every day at 1am"
